// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaDeReservas.API.Database;

#nullable disable

namespace SistemaDeReservas.API.Migrations
{
    [DbContext(typeof(ApiDbContext))]
    [Migration("20250420023531_NuevaActualizada")]
    partial class NuevaActualizada
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.4");

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.ClienteEntity", b =>
                {
                    b.Property<int>("ClienteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("apellido");

                    b.Property<string>("DocumentoId")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("documento_id");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("ClienteId");

                    b.ToTable("clientes");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.HabitacionEntity", b =>
                {
                    b.Property<int>("HabitacionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("habitacion_id");

                    b.Property<int>("Capacidad")
                        .HasColumnType("INTEGER")
                        .HasColumnName("capacity");

                    b.Property<string>("Descripción")
                        .HasColumnType("TEXT")
                        .HasColumnName("description");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disponible");

                    b.Property<int>("HotelId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("numero");

                    b.Property<decimal>("PrecioPorNoche")
                        .HasColumnType("TEXT")
                        .HasColumnName("precio_por_noche");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("tipo");

                    b.HasKey("HabitacionId");

                    b.HasIndex("HotelId");

                    b.ToTable("habitaciones");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.HotelEntity", b =>
                {
                    b.Property<int>("HotelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("hotel_id");

                    b.Property<string>("Ciudad")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("ciudad");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT")
                        .HasColumnName("direccion");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT")
                        .HasColumnName("email");

                    b.Property<int>("Estrellas")
                        .HasColumnType("INTEGER")
                        .HasColumnName("estrellas");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<string>("Pais")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("pais");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("telefono");

                    b.HasKey("HotelId");

                    b.ToTable("hoteles");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.PagoEntity", b =>
                {
                    b.Property<int>("PagoId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("pago_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaPago")
                        .HasColumnType("TEXT")
                        .HasColumnName("fecha_pago");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("metodo_pago");

                    b.Property<int>("ReservaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reserva_id");

                    b.HasKey("PagoId");

                    b.HasIndex("ReservaId");

                    b.ToTable("pagos");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.ReservaEntity", b =>
                {
                    b.Property<int>("ReservaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("reserva_id");

                    b.Property<int>("ClienteId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cliente_id");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("estado");

                    b.Property<DateOnly>("FechaFin")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaFin");

                    b.Property<DateOnly>("FechaInicio")
                        .HasColumnType("TEXT")
                        .HasColumnName("fechaInicio");

                    b.Property<int>("HabitacionId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("habitacion_id");

                    b.Property<decimal>("TotalPago")
                        .HasColumnType("TEXT")
                        .HasColumnName("total_pago");

                    b.HasKey("ReservaId");

                    b.HasIndex("ClienteId");

                    b.HasIndex("HabitacionId");

                    b.ToTable("reservas");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.ServicioAdicionalEntity", b =>
                {
                    b.Property<int>("ServicioAdicionalId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("servicio_adicional_id");

                    b.Property<string>("Descripción")
                        .HasColumnType("TEXT")
                        .HasColumnName("descripcion");

                    b.Property<bool>("Disponible")
                        .HasColumnType("INTEGER")
                        .HasColumnName("disponible");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasColumnName("nombre");

                    b.Property<decimal>("Precio")
                        .HasColumnType("TEXT")
                        .HasColumnName("precio");

                    b.Property<int>("ReservaId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("reserva_id");

                    b.HasKey("ServicioAdicionalId");

                    b.HasIndex("ReservaId");

                    b.ToTable("servicio_adicional");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.HabitacionEntity", b =>
                {
                    b.HasOne("SistemaDeReservas.API.Database.Entities.HotelEntity", "Hotel")
                        .WithMany("Habitaciones")
                        .HasForeignKey("HotelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.PagoEntity", b =>
                {
                    b.HasOne("SistemaDeReservas.API.Database.Entities.ReservaEntity", "Reserva")
                        .WithMany("Pagos")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.ReservaEntity", b =>
                {
                    b.HasOne("SistemaDeReservas.API.Database.Entities.ClienteEntity", "Cliente")
                        .WithMany("Reservas")
                        .HasForeignKey("ClienteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SistemaDeReservas.API.Database.Entities.HabitacionEntity", "Habitacion")
                        .WithMany("Reservas")
                        .HasForeignKey("HabitacionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cliente");

                    b.Navigation("Habitacion");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.ServicioAdicionalEntity", b =>
                {
                    b.HasOne("SistemaDeReservas.API.Database.Entities.ReservaEntity", "Reserva")
                        .WithMany("ServiciosAdicionales")
                        .HasForeignKey("ReservaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reserva");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.ClienteEntity", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.HabitacionEntity", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.HotelEntity", b =>
                {
                    b.Navigation("Habitaciones");
                });

            modelBuilder.Entity("SistemaDeReservas.API.Database.Entities.ReservaEntity", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("ServiciosAdicionales");
                });
#pragma warning restore 612, 618
        }
    }
}
